---
- name: My second playbook
  hosts: webservers
  become: true
  tasks:

  - name: Uninstall apache if needed
    ansible.builtin.apt:
      update_cache: yes
      name: apache2
      state: absent

  - name: Install docker io
    ansible.builtin.apt:
      update_cache: yes
      name: docker.io
      state: present
#      state: absent

  - name: Install python3-pip                                
    ansible.builtin.apt:
#      update_cache: yes
      name: python3-pip
      state: present
##      state: absent

  - name: Install Docker Python module using pip
    pip:
      name: docker
      state: present

  - name: Run DVWA container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      published_ports: 80:80
      state: started
#      restart_policy: always  # Ensure container restarts on VM restart

  - name: Ensure Docker service is started and enabled
    systemd:
      name: docker
      state: started
      enabled: yes
